Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end
	config.vm.box = "ubuntu/trusty64"
	config.vm.provision "docker", run: "always" do|d|
        d.build_image "-t dontbelate /vagrant"
	    d.run "dontbelate"
	end
end
